services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672" # rabbit itself
      - "15672:15672" # management ui

  postgres:
    image: "postgres:alpine"
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "SampleDb"
  lgtm:
    image: grafana/otel-lgtm
    hostname: lgtm
    container_name: lgtm
    ports:
      - "3000:3000" # ui
      - "4317:4317" # otlp gRPC
      - "4318:4318" # otlp HTTP
#  jaeger:
#    image: jaegertracing/all-in-one:1
#    hostname: jaeger
#    container_name: jaeger
#    ports:
#      - "16686:16686" # ui
#      - "4317:4317" # otel grpc